dotfiles:
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*', '.github/*', '.gitignore', '.terraform.lock.hcl', '.editorconfig']

playlist:
  - changed-files:
    - any-glob-to-any-file: ['main.tf', 'variables.tf', 'outputs.tf', 'phantom-blood.tf', 'battle-tendency.tf', 'stardust-crusaders.tf', 'diamond-is-unbreakable.tf', 'vento-aureo.tf', 'stone-ocean.tf', 'steel-ball-run.tf', 'jojolion.tf']

phantom_blood:
  - changed-files:
    - any-glob-to-any-file: ['phantom-blood.tf']

battle_tendency:
  - changed-files:
    - any-glob-to-any-file: ['battle-tendency.tf']

stardust_crusaders:
  - changed-files:
    - any-glob-to-any-file: ['stardust-crusaders.tf']

diamond_is_unbreakable:
  - changed-files:
    - any-glob-to-any-file: ['diamond-is-unbreakable.tf']

vento_aureo:
  - changed-files:
    - any-glob-to-any-file: ['vento-aureo.tf']

stone_ocean:
  - changed-files:
    - any-glob-to-any-file: ['stone-ocean.tf']

steel_ball_run:
  - changed-files:
    - any-glob-to-any-file: ['steel-ball-run.tf']

jojolion:
  - changed-files:
    - any-glob-to-any-file: ['jojolion.tf']

the_jojo_lands:
  - changed-files:
    - any-glob-to-any-file: ['the-jojo-lands.tf']
