name: Lint

on:
  pull_request: {}

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v4.1.6
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Spellcheck Files
        uses: reviewdog/action-misspell@v1.17.0
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
          reporter: github-pr-review
          filter_mode: file

  tflint:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v4.1.6
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint Terraform
        uses: reviewdog/action-tflint@v1.22.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: file
